### PR TITLE
Add blog for reopening of musalla

### PR DESCRIPTION
**Pull request by BoxlikeShowroomGloomy**
## Request for Change

Add blog for reopning of Musallah.

Did not have time to create an issue or find a new thumbnail or image so please do change both.

Risk : `low` 

Estimated Deployment Date/Time : 2020-02-17 00:00 AM

### CODE REVIEW

**Comment by BoxlikeShowroomGloomy** [comment]
I reused some older images. I will be merging this change myself due to time constraints.

**Comment by ragaeeb** [comment]
Just a small note. By convention I include into each update, an entry in the `CHANGELOG.MD` file, and I also bump the version number of `package.json` as well as `package-lock.json` to match the version in the release tag.

**Comment by BoxlikeShowroomGloomy** [comment]
I did not realize that, my bad. You should checkout the [standard-version](https://www.npmjs.com/package/standard-version) npm module, might make this easier. Also, adding these details to the `README.md` would help as well.

**Comment by ragaeeb** [comment]
> I did not realize that, my bad. You should checkout the [standard-version](https://www.npmjs.com/package/standard-version) npm module, might make this easier. Also, adding these details to the `README.md` would help as well.

Will do that now.

**Comment by ragaeeb** [comment]
As for the `standard-version` module, I came across it before but wasn't able to get that working with the GitHub pipeline (ie: deploy actions). If you can figure out how to get that working, please add that in so it's easier to maintain.

**Pull request merged**
